doctrine_mongodb:
  connections:
    default:
      server: '%mongodb_server%'
      options: {}
  default_database: '%env(resolve:MONGODB_COLLECTION)%'
  document_managers:
    default:
      auto_mapping: true
      mappings:
        App:
          is_bundle: false
          dir: '%kernel.project_dir%/src/Document'
          prefix: 'App\Document'
          alias: App
          type: attribute