version: '3.7'

services:
  engapi.localhost:
    build: .
    container_name: engapi.localhost
    restart: always
    ports:
      - '443:443'
    volumes:
      - ./:/var/www/html
    depends_on:
      - 'mongodb'

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - ./docker/database/mongodb:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'
