version: '3.7'

services:
  eng_api_nginx:
    build: ./docker/nginx
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - 'php'
    networks:
      - 'external_network'
      - 'internal'

  php:
    build: ./docker/php
    restart: on-failure
    volumes:
      - ./:/var/www/html
    depends_on:
      - 'mongodb'
      - 'rabbitmq'
    networks:
      - 'internal'

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - ./docker/database/mongodb:/data/db
    networks:
      - 'internal'

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'
    depends_on:
      - 'mongodb'
    networks:
      - 'internal'

networks:
  internal:
    driver: bridge
  external_network:
    name: eng_api_external_network
