parameters:
    mongodb_server: 'mongodb://%env(resolve:MONGODB_LOGIN)%:%env(resolve:MONGODB_PASSWORD)%@mongodb:27017/?authSource=admin'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
