parameters:
    mongodb_server: 'mongodb://%env(resolve:MONGODB_LOGIN)%:%env(resolve:MONGODB_PASSWORD)%@mongodb:27017/?authSource=admin'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventListener\RequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    Symfony\Component\Serializer\Normalizer\ObjectNormalizer: ~

    Symfony\Component\Serializer\Serializer:
        arguments:
            - [ '@Symfony\Component\Serializer\Normalizer\ObjectNormalizer' ]
            - [ '@serializer.encoder.json' ]