parameters:
    form.allow_extra_fields: false

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\EventListener\RequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    Doctrine\Persistence\ManagerRegistry: '@Doctrine\Bundle\MongoDBBundle\ManagerRegistry'

    Symfony\Component\Form\Extension\Core\CoreExtension:
        arguments:
            - '%form.allow_extra_fields%'

    Symfony\Component\Notifier\Transport\Discord\DiscordTransport:
        arguments:
            - 'https://discord.com/api/webhooks/1137740054396158015/w98wlCthFFeFWX1MtIR-VwLvWHKqE3nACX1-lO8DoYCnHv8neVP4eVy410VoNhd5TCEP'
